### ISSUE TITLE
Figure out a solution to allow multiple feedback

### ISSUE THREAD

**Issue by sterlingwalker** [sterlingwalker/humanocity-server#10]
- Parsing in an option or finding a more efficient way to store it in firebase

**Comment by yonimn2000** [comment]
Couldn't we just have random ID's for feedback? Then each feedback could have a unique id and the employee id of the submitting employee.

**Comment by sterlingwalker** [comment]
> Couldn't we just have random ID's for feedback? Then each feedback could have a unique id and the employee id of the submitting employee.

Yea so having a unique id is important. Would you recommend having a  unique feedback id in the model and then have this unique id be the way that it's indexed in firebase?

**Comment by yonimn2000** [comment]
Yeah, I think it would be easy to work with the feedback this way when making calls to the DB.
