### ISSUE TITLE
"/timeoffs" endpoint broke in recent update

### ISSUE THREAD

**Issue by sterlingwalker** [sterlingwalker/humanocity-server#21]
When I hit the endpoint it just returns an empty array. I tested a few branches created within the last 2 weeks and this endpoint was broken on all of them. I suspect it has to do with `L72` in the `ReadController` when I removed the `!timeOff.isExpired()` condition it seemed to work as normal. That logic may need to be revised.

**Comment by yonimn2000** [comment]
It means that everything is working as it is supposed to! All time offs expired today. I added a new one through Firebase for next week and it works. 😎

**Comment by sterlingwalker** [comment]
Ope my bad 🤣, you are completely right! Thank you for clarification, that makes sense!
